---

- name: Create directories
  file:
    state: directory
    mode: "0744"
    path: "{{ item }}"
  with_items:
    - "{{ install_dir }}"
    - "{{ apps_dir }}"
    - "{{ config_dir }}"
    - "{{ logs_dir }}"
    - "{{ run_dir }}"
  tags: ["dirs"]
